package main

// Arrangement recipes reuse the built-in lyric sections; bracketed lines guide performance.
var structures = []Preset{
	{"Classic", "Verse → chorus → verse → chorus → bridge → chorus", "[Intro]\nVerse 1\nChorus\nVerse 2\nChorus\nBridge\nChorus\n[Outro]"},
	{"Hook first", "Start with the hook. Keep it moving.", "Chorus\nVerse 1\nChorus\nVerse 2\nBridge\nChorus x2\n[Outro]"},
	{"Slow build", "A quiet opening, a big finish", "[Soft instrumental intro]\nVerse 1\nVerse 2\n[Build]\nChorus\nBridge\n[Full band]\nChorus x2\n[Fade out]"},
	{"Electronic", "Builds, drops, and a breakdown", "[Intro]\nVerse 1\n[Build]\nChorus\n[Drop]\nVerse 2\n[Breakdown]\nChorus\n[Final drop]\n[Outro]"},
	{"Short & sweet", "A verse and a repeatable hook", "[Intro]\nVerse 1\nChorus x2\n[Outro]"},

	// Genre-focused recipes.
	{"Pop · double final chorus", "Pop · early hook, short bridge, bigger final refrain", "[Short instrumental intro]\nVerse 1\n[Build into the hook]\nChorus\nVerse 2\nChorus\n[Strip back to voice and keys]\nBridge\n[Full band, add vocal harmonies]\nChorus x2\n[Short outro]"},
	{"Hip-hop · hook and two verses", "Hip-hop · opening hook, two verses, beat-switch bridge", "[Four-bar beat intro]\nChorus\nVerse 1\nChorus\nVerse 2\n[Beat switch, half-time feel]\nBridge\n[Original beat returns]\nChorus\n[Instrumental outro]"},
	{"Funk · vamp and breakdown", "Funk / Vulfpeck · pocket, unison stops, bass-led break", "[Tight bass-and-drum vamp]\nVerse 1\nChorus\n[Two-bar unison stop and restart]\nVerse 2\nChorus\n[Breakdown: bass, drums, and clavinet]\nBridge\n[Bass-led instrumental break]\nChorus\n[Short ensemble stabs, stop together]"},
	{"Country · story and refrain", "Country · two narrative verses, intimate bridge, refrain", "[Acoustic guitar intro]\nVerse 1\nChorus\nVerse 2\nChorus\n[Pedal steel instrumental turnaround]\nBridge\n[Pull back to voice and acoustic guitar]\nChorus\n[Gentle instrumental outro]"},
	{"Gospel · call and response", "Gospel / soul · solo opening, choir lift, extended ending", "[Solo voice and piano opening]\nVerse 1\n[Choir answers the lead]\nChorus\nVerse 2\n[Add handclaps and organ]\nChorus\n[Strip back, lead vocal testimony]\nBridge\n[Full choir, rising intensity]\nChorus x2\n[Hold final chord, voices resolve together]"},
	{"Metal · half-time breakdown", "Metal · riff intro, melodic hook, heavy bridge", "[Heavy instrumental riff intro]\nVerse 1\nChorus\n[Return to the opening riff]\nVerse 2\nChorus\n[Half-time breakdown, low chugs and toms]\nBridge\n[Guitar solo over the opening riff]\nChorus\n[Final riff, abrupt stop]"},
	{"Dance · build and two drops", "House / D&B · two drops separated by a quiet breakdown", "[Percussion intro, gradual bass entrance]\nVerse 1\n[Build: rising synths, filtered drums]\nChorus\n[First instrumental drop]\n[Breakdown: pads and sparse percussion]\nVerse 2\nBridge\n[Second build, brief silence]\nChorus\n[Final instrumental drop, expanded lead melody]\n[DJ-friendly percussion outro]"},
	{"Ambient · slow drift", "Instrumental · evolving textures, one swell, long decay", "[Instrumental]\n[Intro: a single sustained tone]\n[Gradually introduce soft harmonic layers]\n[Main motif emerges, sparse and unhurried]\n[Subtle low pulse enters]\n[One broad harmonic swell]\n[Remove layers until only the opening tone remains]\n[Long natural decay]"},
	{"Post-rock · long crescendo", "Instrumental · recurring motif, patient rise, quiet return", "[Instrumental]\n[Clean guitar motif alone]\n[Bass enters beneath the same motif]\n[Light percussion, restrained repetition]\n[Second guitar introduces a counter-melody]\n[Build gradually with toms and cymbals]\n[Full-band distorted climax, retain the opening motif]\n[Sudden drop to the original clean guitar]\n[Let the last note decay]"},
	{"Jazz · head, solos, head", "Instrumental · main theme, solo exchanges, theme reprise", "[Instrumental]\n[Short rhythm-section intro]\n[Head: state the main melody]\n[Piano solo over the form]\n[Bass solo, drums play softly]\n[Trade short phrases with the drums]\n[Head: return to the main melody]\n[Repeat the final phrase, ensemble ending]"},
	{"Folk · unfolding story", "Folk · consecutive verses, late refrain, gentle coda", "[Fingerpicked acoustic intro]\nVerse 1\n[Short instrumental answer]\nVerse 2\n[Add a second voice and soft strings]\nBridge\n[First full refrain, all voices together]\nChorus\n[Acoustic coda, return to the opening motif]"},
	{"Cinematic · three acts", "Instrumental · establish a theme, tension, final resolution", "[Instrumental]\n[Act I: intimate piano theme]\n[Strings quietly develop the melody]\n[Act II: unresolved harmony, low percussion pulse]\n[Brass and strings build tension]\n[Brief silence]\n[Act III: full-orchestra return of the opening theme]\n[Quiet piano epilogue]"},

	// Original artist-inspired pacing, not transcriptions of particular songs.
	{"Thrice · quiet to heavy", "Artist · intimate opening, atmospheric bridge, final surge", "[Intro: delayed clean guitar and low organ]\n[Restrained voice, sparse rhythm section]\nVerse 1\n[Full-band lift, open ringing chords]\nChorus\n[Pull the guitars back, bass carries the movement]\nVerse 2\nChorus\n[Atmospheric instrumental passage, evolving guitar textures]\n[Quiet start, gradually build intensity]\nBridge\n[Heavy final chorus, raw vocal delivery]\nChorus\n[Unresolved guitar ambience fades]"},
	{"Thrice · shifting sections", "Artist · riff opening, off-center groove, unexpected coda", "[Intro: interlocking guitar riff, syncopated drums]\nVerse 1\n[Open up the harmony and rhythm]\nChorus\n[Instrumental transition, change the rhythmic emphasis]\nVerse 2\n[Drop to organ and voice]\nBridge\n[Build from near silence into heavy guitars]\nChorus\n[Extended instrumental coda, transform the opening riff]\n[Quiet final chord]"},
	{"Chevelle · tension and release", "Artist · sparse tense verses, huge hooks, half-time bridge", "[Short low-tuned riff intro]\n[Restrained vocals, muted guitar, prominent bass]\nVerse 1\n[Explosive full-band chorus]\nChorus\n[Return to the tight opening groove]\nVerse 2\nChorus\n[Half-time bridge, dissonant guitar accents]\nBridge\n[Brief silence before the final impact]\nChorus x2\n[Opening riff reprise, hard stop]"},
	{"Chevelle · riff-driven slow burn", "Artist · hypnotic riff, delayed hook, escalating ending", "[Hypnotic bass-and-guitar ostinato]\n[Quiet vocal delivery, drums held back]\nVerse 1\n[Instrumental riff variation, slowly increase pressure]\nVerse 2\n[First full-band chorus, release the tension]\nChorus\n[Low ominous instrumental break]\nBridge\n[Final chorus, higher vocal intensity]\nChorus\n[Extended heavy riff outro, abrupt cutoff]"},
	{"mewithoutYou · spoken-word crescendo", "Artist · unfolding narrative, late refrain, cathartic ending", "[Sparse wiry electric guitar figure, bass pulse]\n[Conversational spoken delivery, restless drum kit]\nVerse 1\n[Short instrumental transition, bass takes the melody]\n[More urgent speech, guitars become ragged]\nVerse 2\n[Band drops to a quiet pulse]\n[Half-spoken bridge, gradually rise to impassioned shouts]\nBridge\n[First full refrain, cathartic shouted vocals over distorted guitars]\nChorus\n[Extended full-band instrumental release]\n[Clean electric guitar returns, feedback slowly decays]"},
	{"mewithoutYou · angular post-hardcore", "Artist · jagged riffs, spoken tension, explosive coda", "[Interlocking electric guitar riff, melodic bass, full drum kit]\n[Urgent spoken delivery over a tense syncopated groove]\nVerse 1\n[Abrupt distorted-guitar surge, impassioned shouts]\nChorus\n[Pull back to wiry clean electric guitar and moving bass]\n[More insistent speech, restless tom fills]\nVerse 2\n[Brief rhythmic stop, bass and drums re-enter alone]\n[Spoken bridge builds into raw shouting]\nBridge\n[Full-band return, jagged guitars and crashing cymbals]\nChorus\n[Extended instrumental coda, twist the opening riff into dissonant overdrive]\n[Hard stop, guitar feedback decays]"},
}
